baseURL = "https://Lamhuy0489.github.io/workshop/"
relativeURLs = true
canonifyURLs = true
buildFuture = true
defaultContentLanguage = "en"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = "FCAJ Workforce Bootcamp 2026 - Báo cáo thực tập tốt nghiệp & Workshop kiến trúc Serverless Hybrid Document OCR, Parsing & Translation Platform trên AWS - Lâm Quang Huy (MSSV: 0212267)"
  author = "Lâm Quang Huy"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
[Languages.en]
title = "Hybrid Document OCR & Parsing Platform on AWS"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[Languages.vi]
title = "Báo cáo thực tập - Hybrid Document OCR trên AWS"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true